### ISSUE TITLE
Rosdepにて一部の依存パッケージがインストールされない。

### ISSUE THREAD

**Issue by Alpaca-kun** [pwri-opera/ic120_ros#4]
土木研究所 技術推進本部 先端技術チーム　へ

初めまして、
sim_physx シミュレーターを使用したいのですが、一部のパッケージが正常にインストール出来ません。
具体的には ```ic120``` と ```zx120``` のROSパッケージを ```rosdep``` にてインストールしようとする際に、以下のエラーが返されます：

```bash
$ rosdep install --from-paths ~/OPERA_ws/src --ignore-src -r -y

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ic120_navigation: Cannot locate rosdep definition for [ic120_hander]
zx120_navigation: Cannot locate rosdep definition for [ic120_hander]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully 
```

```ic120_ros``` のリポジトリを検索いたしましたが、```ic120_hander``` に関する記述は見受けられませんでした。
```ic120_hander``` とはどのようなパッケージですか。
また、上記の依存性はどのように解消したらよろしいのでしょうか。

**Comment by maopotcha** [comment]
@Alpaca-kun 
情報提供をありがとうございます。本件、だいたい原因と対応方法について見当がついたのですが、動作確認含めて今しばらくお時間をいただきます。
本件、リプライが遅くなりまして申し訳ありません。

**Comment by Alpaca-kun** [comment]
@maopotcha 
ご返信ありがとうございます。本件の状況了解致しました。
引き続き本件に関する通知を受けたいので、Issueをオープン状態に保ってもよろしいでしょうか。

**Comment by maopotcha** [comment]
@Alpaca-kun 
issueをオープン状態に保っていただいて問題ありません。
よろしくお願いいたします。

**Comment by maopotcha** [comment]
@Alpaca-kun 
いただいたissueに対応する修正を施しました。結局、依存関係がないパッケージの記述がpackage.xmlに残ってしまっていたのが原因であり、それを削除しました。
READMEに記載した手順で依存関係の解決を行っていただければ、ご報告いただいたERRORがなくなるのではないかと思います。もしよろしければ、確認の上、結果をご連絡いただけますでしょうか。
（当方でもdocker環境下でビルドと実行時の動作確認はしております）

本件、もし1週間以内に何もリプライがなければ、こちらの判断で勝手ながら一旦closeとさせていただければ、と存じます。

**Comment by Alpaca-kun** [comment]
返信が遅くなり申し訳ございません。
こちら側でもエラーの解消を確認できました。
別件ですが、併せて私が```zx120_ros```で申請したプルリクエストを取り下げようと思います。

ご対応いただき、誠にありがとうございました。
